language: node_js
node_js:
  - "12.13.1"

matrix:
  fast_finish: true

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.19.1
  - export PATH="$HOME/.yarn/bin:$PATH"

before_script:
  - yarn

script:
  - yarn test
  - yarn build
  - yarn netlify:deploy

cache:
  yarn: true
  timeout: 10000
  directories:
    - node_modules

# deploy to netlify
after_success:
  - chmod +x ./deploy.sh
  - ./deploy.sh

git:
  depth: 3

branches:
  # safelist
  only:
    - master
  # blocklist
  except:
    - experimental

notifications:
  email: false
